### ISSUE TITLE
Repository status

### ISSUE THREAD

**Issue by untereiner** [camunda-community-hub/zeebe-cloudevents-router#9]
Hi,
I am interested in using CloudEvents with Zeebe/Camunda.
This repository seems to be a good starting point. 
However it looks like abandoned. 
Where could I start to give him life back ?

**Comment by celanthe** [comment]
Hi @untereiner! Thank you so much for reaching out. I would be happy to take a look at this repository next week and get back to you as to how you can contribute to this repository. :) Thank you so much for your efforts and interest!

**Comment by untereiner** [comment]
Hi @celanthe! I saw that the repositories working with micronaut are very active lately. Could it be more valuable for the future to transform this cloud-event router from sping to micronaut ?

**Comment by celanthe** [comment]
Hi @untereiner! I think that's a fantastic idea. I also have a few suggestions as well for bringing this extension back to life:

1. Update to the latest [Zeebe version](https://github.com/camunda-community-hub/zeebe-cloud-events-router/issues/8)
2. Update the [dependencies](https://github.com/camunda-community-hub/zeebe-cloud-events-router/issues/7). 

Once these two things are complete, the extension should work with the latest Zeebe version 1.3.0.

3. Improvements could be made to the README -- What does this project do? How does it work? 
4. Additional README improvements that might come after switching to Micronaut -- How do you use the extension/set it up? I would recommend reaching out to the https://github.com/camunda-community-hub/micronaut-zeebe-client team and asking how you might best collaborate. I'm sure they would be interested in helping out! :) 
5. Update the [contributor guide](https://github.com/camunda-community-hub/zeebe-cloud-events-router/blob/master/CONTRIBUTING.md)

I was wondering if you would like to become a Maintainer for this project? If so, I would be happy to invite you to join as a Member of the Camunda Community hub, and grant you the necessary permissions to Maintain this extension moving forward.

Thank you so much for your contributions. I look forward to the progression of this extension.

**Comment by tobiasschaefer** [comment]
Hi @untereiner ,

I'm the lead maintainer of the three Micronaut projects listed on the Camunda Community Hub and excited that you are also interested in running Zeebe on Micronaut.

I'm not familiar with the zeebe-cloud-events-router but it sounds to me you could use the micronaut-zeebe-client as a dependency for this project to reduce boiler-plate code.

Note: I just released v1.2.0 of micronaut-zeebe-client which includes the latest Zeebe 1.3.0 and Micronaut 3.2.6.

Shall we have a talk? Feel free to contact me at tobias.schaefer@novatec-gmbh.de 

@celanthe : thanks for reaching out to me

**Comment by untereiner** [comment]
Hi @tobiasschaefer,

I will first update the existing repository and then will look at how I can add the micronaut-zeebe-client as a dependency.
I am starting with the Micronaut framework and it is not my main focus. So I may be slow :)
I will not hesitate to contact you !

**Comment by untereiner** [comment]
Hi, I working a bit deeper and it raised concerns:
1. About the dependencies. For example [this one](https://github.com/salaboy/zeebe-cloud-events-java-sdk) doesn't have any licence nor maven module. @salaboy hasn't responded yet.
2. There are a bunch of modifications to make this repository produce a module to the maven repository using the github pipeline.

May I have the clear ability to do what it needs to be done to make it work ?

**Comment by celanthe** [comment]
Hi @untereiner -- Indeed. I sent you an invite to join the Camunda Community Hub. Once you accept the invite I can grant you Maintainer permissions so you can update those dependencies and add licenses/Maven modules as needed. 

I hope that makes sense! Also, re: Maven uploading -- we have a GitHub actions workflow available that you can utilize at: https://github.com/camunda-community-hub/community-action-maven-release

**Comment by celanthe** [comment]
Hi @untereiner -- I've made you the new Maintainer for this project. You should have the ability now to update those dependencies and add licenses and Maven modules as needed. :) If there's anything else I can help with please don't hesitate to ask.

**Comment by untereiner** [comment]
Hi @celanthe ! Thank you. I started the work on my fork in the meanwhile. 
I have still some questions:
- I tried to mimic the deployment workflow but I missed the credentials of maven and nexus. The goal `goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy` returns `status: 401 Unauthorized`
- Should I use the maven-url `oss.sonatype.org` or  `s01.oss.sonatype.org`

**Comment by celanthe** [comment]
Hi @untereiner! Thank you for your awesome work so far! Here are the answers to your questions:

1. I've added this repository to our infrastructure configuration, you should be able to utilize the Github Actions workflow now! 
2. s01.oss.sonatype.org 
3. That should be fine, whenever you do rename it just let me know and I will update its name in the infrastructure configuration! :)

**Comment by untereiner** [comment]
Hi Again 🙂
I am sorry but I don’t have enough permissions on this repository to do the name changing by myself.

**Comment by celanthe** [comment]
Hi @untereiner! No worries, I can look into this and will get back to you ASAP. :) Thank you again for all your hard work so far!

**Comment by celanthe** [comment]
Hi @untereiner! I saw your recent merged PR that updated the credentials for the workflow. My apologies for suggesting s01. the oss.sonatype.org change you made in #19 should hopefully resolve the issue. 

If you'd like to learn about the change relating to s01.sonatype vs. oss.sonatype, there's a blog post viewable at: https://central.sonatype.org/news/20210223_new-users-on-s01/#why-are-we-doing-this

**Comment by untereiner** [comment]
Hi @celanthe! It's fine. I found it out! I am still trying to find a clean way to deploy this multi module project on sonatype. I will maybe put everything under a common groupID.

**Comment by celanthe** [comment]
Awesome! :) That's great news, @untereiner! Looking forward to it! Thank you kindly for your fantastic contributions to Camunda. They're very much appreciated.

**Comment by celanthe** [comment]
Hi @untereiner! I just wanted to thank you again for bringing this extension back to life! :) I am now going to close this issue. If you have any additional questions please feel free to reach out to @camunda-community-hub/devrel! :)
